# Generated by Django 5.1.4 on 2025-01-14 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('cost_orders', models.FloatField(verbose_name='Сумма покупок')),
                ('count_orders', models.IntegerField(verbose_name='Количество заказов')),
                ('count_rejects', models.IntegerField(verbose_name='Количество отказов')),
                ('percent_buy', models.FloatField(verbose_name='Процент выкупа')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('count_storage', models.IntegerField(verbose_name='Количество на складе')),
                ('count_sells', models.IntegerField(verbose_name='Количество продаж')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_orders', models.IntegerField(verbose_name='Количество заказов')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('address_delivery', models.CharField(max_length=100, verbose_name='Адрес доставку')),
                ('date_order', models.DateField(verbose_name='Дата заказа')),
                ('date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.user')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.user')),
            ],
        ),

    ]
