# Generated by Django 5.1.4 on 2025-01-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_cost_product_price_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
