# Generated by Django 5.1.4 on 2025-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_typeproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
    ]
