# Generated by Django 5.1.4 on 2025-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_typeproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type_products/'),
        ),
    ]
