# Generated by Django 5.1.4 on 2025-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_typeproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_sells',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество продаж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_storage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
